"""fix relation

Revision ID: 48c8f81a2d5b
Revises: 9ccf8aafaed0
Create Date: 2023-07-19 13:55:00.877024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48c8f81a2d5b"
down_revision = "9ccf8aafaed0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comment", sa.Column("article_id", sa.Integer(), nullable=True)
    )
    op.create_index(op.f("ix_comment_id"), "comment", ["id"], unique=False)
    op.create_unique_constraint(None, "comment", ["article_id"])
    op.drop_constraint(
        "comment_article_comment_fkey", "comment", type_="foreignkey"
    )
    op.create_foreign_key(None, "comment", "article", ["article_id"], ["id"])
    op.drop_column("comment", "article_comment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comment",
        sa.Column(
            "article_comment", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.create_foreign_key(
        "comment_article_comment_fkey",
        "comment",
        "article",
        ["article_comment"],
        ["id"],
    )
    op.drop_constraint(None, "comment", type_="unique")
    op.drop_index(op.f("ix_comment_id"), table_name="comment")
    op.drop_column("comment", "article_id")
    # ### end Alembic commands ###
