name: Code checks
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ## Environment  variable
      TESTING_HOST: localhost
      TESTING_PORT: 5432
      TESTING_NAME: mock
      TESTING_USER: mock
      TESTING_PASS: mock

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ env.TESTING_NAME }}
          POSTGRES_USER: ${{ env.TESTING_USER }}
          POSTGRES_PASSWORD: ${{ env.TESTING_PASS }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5
      - name: Install deps
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: Run flake8
        run: poetry run flake8
      - name: Wait for postgres to start
        run: |
          until nc -z -v -w30 localhost 5432
          do
          echo "Waiting for postgres start."
          sleep 1
          done

      - name: Set up .env for tests
        run: |
            echo "DB_HOST=${TESTING_HOST}" >> .env
            echo "DB_PORT=${TESTING_PORT}" >> .env
            echo "DB_NAME=${TESTING_NAME}" >> .env
            echo "DB_USER=${TESTING_USER}" >> .env
            echo "DB_PASS=${TESTING_PASS}" >> .env
      - name: Run tests
        run: poetry run pytest